version: "2"


linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/aamir-al/cineapi

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
