INSERT INTO movies (title, year, runtime, genres) VALUES
    ('The Godfather',                          1972, 175, '{"drama","crime"}'),
    ('The Shawshank Redemption',               1994, 142, '{"drama"}'),
    ('Pulp Fiction',                           1994, 154, '{"crime","drama"}'),
    ('Schindler''s List',                      1993, 195, '{"drama","history"}'),
    ('The Dark Knight',                        2008, 152, '{"action","crime","drama"}'),
    ('Forrest Gump',                           1994, 142, '{"drama","romance"}'),
    ('Inception',                              2010, 148, '{"action","sci-fi","thriller"}'),
    ('Interstellar',                           2014, 169, '{"adventure","drama","sci-fi"}'),
    ('The Matrix',                             1999, 136, '{"action","sci-fi"}'),
    ('Goodfellas',                             1990, 146, '{"crime","drama"}'),
    ('Fight Club',                             1999, 139, '{"drama","thriller"}'),
    ('The Silence of the Lambs',               1991, 118, '{"crime","drama","thriller"}'),
    ('Parasite',                               2019, 132, '{"drama","thriller"}'),
    ('Whiplash',                               2014, 107, '{"drama","music"}'),
    ('The Grand Budapest Hotel',               2014,  99, '{"adventure","comedy","crime"}'),
    ('La La Land',                             2016, 128, '{"drama","music","romance"}'),
    ('Get Out',                                2017, 104, '{"horror","mystery","thriller"}'),
    ('1917',                                   2019, 119, '{"drama","war"}'),
    ('Dune',                                   2021, 155, '{"adventure","drama","sci-fi"}'),
    ('Everything Everywhere All at Once',      2022, 139, '{"action","adventure","comedy"}');
